-- =============================================================================
-- Migration: Enable pgvector and add semantic search for ai_analyses
-- Date: 2026-02-28
-- =============================================================================

-- Enable pgvector extension (no-op if already enabled)
CREATE EXTENSION IF NOT EXISTS vector;

-- ---------------------------------------------------------------------------
-- Migrate embedding column from text (JSON string) to vector(1536)
-- Existing rows: PostgreSQL casts the JSON array string directly to vector.
-- Safe because all existing embeddings were generated by text-embedding-3-small
-- and stored as JSON.stringify(number[1536]).
-- ---------------------------------------------------------------------------
ALTER TABLE ai_analyses
  ALTER COLUMN embedding TYPE vector(1536)
  USING embedding::vector(1536);

-- ---------------------------------------------------------------------------
-- HNSW index for fast approximate cosine similarity search
-- m=16, ef_construction=64 are solid defaults for 1536-dim embeddings.
-- ---------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS ai_analyses_embedding_hnsw
  ON ai_analyses
  USING hnsw (embedding vector_cosine_ops)
  WITH (m = 16, ef_construction = 64);

-- ---------------------------------------------------------------------------
-- RPC: search_historical_analyses
--
-- Parameters:
--   query_embedding      vector(1536)  — embedding of the user's search query
--   similarity_threshold float         — minimum cosine similarity (default 0.7)
--   match_count          int           — max rows to return (default 5)
--   p_user_id            text          — filter to a specific user (NULL = all)
--
-- Returns rows ordered by descending cosine similarity, with similarity score.
-- The <=> operator is pgvector's cosine distance; similarity = 1 - distance.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION search_historical_analyses(
  query_embedding      vector(1536),
  similarity_threshold float   DEFAULT 0.7,
  match_count          int     DEFAULT 5,
  p_user_id            text    DEFAULT NULL
)
RETURNS TABLE (
  id                uuid,
  user_id           text,
  summary           text,
  bias              text,
  market_snapshot   jsonb,
  structured_output jsonb,
  created_at        timestamptz,
  similarity        float
)
LANGUAGE sql
STABLE
AS $$
  SELECT
    id,
    user_id,
    summary,
    bias,
    market_snapshot,
    structured_output,
    created_at,
    1 - (embedding <=> query_embedding) AS similarity
  FROM ai_analyses
  WHERE
    (p_user_id IS NULL OR user_id = p_user_id)
    AND 1 - (embedding <=> query_embedding) >= similarity_threshold
  ORDER BY embedding <=> query_embedding
  LIMIT match_count;
$$;

-- ---------------------------------------------------------------------------
-- VERIFICATION QUERIES (run manually after applying migration)
-- ---------------------------------------------------------------------------
-- 1. Confirm pgvector is enabled:
--    SELECT extname FROM pg_extension WHERE extname = 'vector';
--
-- 2. Confirm embedding column type:
--    SELECT column_name, data_type, udt_name
--    FROM information_schema.columns
--    WHERE table_name = 'ai_analyses' AND column_name = 'embedding';
--    → udt_name should be 'vector'
--
-- 3. Confirm HNSW index exists:
--    SELECT indexname, indexdef
--    FROM pg_indexes
--    WHERE tablename = 'ai_analyses' AND indexname = 'ai_analyses_embedding_hnsw';
--
-- 4. Test RPC (replace with a real 1536-dim vector):
--    SELECT * FROM search_historical_analyses(
--      '[0.1, 0.2, ...]'::vector(1536), 0.5, 3, NULL
--    );
-- ---------------------------------------------------------------------------
